server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 100M;

    types {
        text/html                   html htm;
        text/css                    css;
        application/javascript      js;
        application/json            json;
        image/png                   png;
        image/jpeg                  jpg jpeg;
        image/gif                   gif;
        image/webp                  webp;
        image/x-icon                ico;
        image/svg+xml               svg svgz;
        font/woff                   woff;
        font/woff2                  woff2;
        video/mp4                   mp4;
        video/webm                  webm;
        audio/mpeg                  mp3;
    }

    location ~* \.(mp4|webm)$ {
        add_header Accept-Ranges bytes;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
