server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 200M;

    location ~* \.(mp4|webm)$ {
        add_header Accept-Ranges bytes;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
